### ISSUE TITLE
Please do not share the solutions 

### ISSUE THREAD

**Issue by frankbass3** [Kulbear/deep-learning-coursera#22]
I would not recommed you to share the problems solutions of the all courses 

1) the course certification will be taken also by people which dose not know anything about machine learning and will get a certification and will share it in the CVs and in Linkedin  
boasting about deep learning certifications

2)  As second inside the course you signed up a document in which you can not share the code solutions 

3) please do not share more solutions or i will send your link to cursera and the repository will be closed.

thank you.

**Comment by meethariprasad** [comment]
@frankbass3  This is so immature. You must understand that scope of coursera solution sharing must & should only limit to Coursera Discussion threads. It has no say over if a student save his work in github. @Kulbear has not told anyone to look in to his code or repository.  Are you aware that Coursera assignment notebooks will not be accessible once course schedule is over & we need to raise a coursera ticket to get our code back? We are living in knowledge sharing era. If some one copies code & gets certificate, then he will never master skills, so he will be already at loss. Just having certificate has no merits. I follow others & many people follow my codes, just to understand the variations/share ideas, so please understand that that is also a form of knowledge sharing. Grow up! I had to be harsh because, I absolutely don't tolerate who threaten the good people publicly by using the words "stop it" and so on.

**Comment by frankbass3** [comment]
i think this is over the rules of coursera.

Il Mar 28 Nov 2017, 17:08 meethariprasad <notifications@github.com> ha
scritto:

**Comment by Kulbear** [comment]
@frankbass3 I understand your concerns and @meethariprasad explained some of my thoughts (but not all). I original post some notebooks here just for my friend who is interested in related research BUT NOT going to take the Coursera courses. I've working on deep learning for a long time so basically I'll have a quick look on the course and complete the assignment in maybe just a half hour. So originally I pushed the code very early, that's probably why this repo got a lot of attention. There are some people, probably, use the solution to pass the course, as @meethariprasad mentioned, they will benefit nobody. Also, in order to avoid such cases, I didn't have a plan to upload notebooks and quiz for CNN course (and the RNN course) recently. There are hundreds of repo contain the solution for the courses but it seems mine will be presented on the top of search result. 

You can never stop cheaters, but a mature person knows what to do to benefit himself/herself/?self.
